// src/App.tsx
import { Button } from './components/ui/button'

function App() {
  return (
    <div className="h-screen">
      <div className="flex justify-center items-center h-full bg-gray-100">
        <div className="">
          <div className="mb-4">
            <img className="rounded-[50%] mx-auto" src="https://github.com/gtn1024.png" alt="Avatar" />
          </div>
          <div className="flex justify-between">
            <Button variant="link" asChild>
              <a href="mailto:i@gtn1024.me">Contact</a>
            </Button>
            <Button variant="link" asChild>
              <a href="https://github.com/gtn1024">GitHub</a>
            </Button>
            <Button variant="link" asChild>
              <a href="https://blog.gtn1024.me">Blog</a>
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}

export default App

// src/App.vue
<script setup>
</script>

<template>
  <div flex max-w-1200px mx-auto items-start pt-4 gap-8>
    <div w="3/4" bg="#fff">
      <div flex pt-4 pl-4 pb-8 gap-4 bg="#267ad1">
        <div>
          <img src="https://avatars.githubusercontent.com/u/69113276" alt="avatar" width="120" rounded-60px />
        </div>
        <div flex-auto text-white>
          <h1 text-8 leading-14>
            gtn1024
          </h1>
          <!-- <p>
            啥都不会
          </p> -->
        </div>
      </div>
      <div p-4>
        <h2 text-6 pb-2>个人简介</h2>
        <p>
          待会再来补一些简介~
        </p>
      </div>
    </div>
    <div w="1/4" bg="#fff">
      <div w-full>
        <div text-5 flex justify-between items-center m-2>
          <div flex items-center gap-1 leading-8>
            <span class="i-bxs:user" /> 联系方式
          </div>
          <span class="i-icon-park:down" />
        </div>
        <div>
          <div flex justify-between items-center m-2 hover:bg="#f4f4f4">
            <div flex items-center gap-1 ml-6 leading-8>
              <span class="i-material-symbols:mail-outline" />
              <a href="mailto:i@gtn1024.me" target="_blank">
                i@gtn1024.me
              </a>
            </div>
          </div>
          <div flex justify-between items-center m-2 hover:bg="#f4f4f4">
            <div flex items-center gap-1 ml-6 leading-8>
              <span class="i-mdi:github" />
              <a href="https://github.com/gtn1024" target="_blank">
                gtn1024
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
</style>
